#
#
#

application: gifhov2
version: 1
runtime: python27
api_version: 1
threadsafe: true



handlers:
- url: /static/assets/js
  static_dir: static/assets/js
- url: /static/assets/images
  static_dir: static/assets/images
- url: /static/css
  static_dir: static/css
  

- url: /.*
  script: gifhov.application





libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest